name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 10.10.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^6.0.7
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.0
  url_launcher: ^6.2.1
  flutter_vector_icons: ^2.0.0
  country_picker: ^2.0.22

  #Firebase
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_remote_config: ^4.3.4
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.1
  cloud_firestore: ^4.13.1
  firebase_pagination: ^3.0.0
  webview_flutter: ^4.4.2

  auto_size_text: 3.0.0
  flutter_custom_tabs: ^1.2.1

  #image:
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  file_picker: ^6.1.1
  lottie: ^2.7.0

  # PAYMENTS
  phonepe_payment_sdk: ^1.0.3
  flutter_stripe: ^9.4.0
  razorpay_flutter: ^1.3.5
  flutterwave_standard: ^1.0.8
  cinetpay: ^1.0.7
  flutter_paypal_checkout:
    git:
      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/Raj-GMITS/flutter_paystack.git
      ref: master        

  #notifications:
  onesignal_flutter: ^5.0.4
  flutter_typeahead: ^4.8.0

  #chart
  syncfusion_flutter_charts: ^23.1.44

  #map:
  geocoding: ^2.1.1
  flutter_html: ^3.0.0-alpha.3
  flutter_image_stack: ^0.0.7
  android_intent_plus: ^4.0.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/upi_payment/
    - assets/lottie/

